name: When Trump Wins
favicon: null
layout_spectrum: 0.38240059604868293
typography_spectrum: 0.8636951902881265
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.49427325604483485
  lightness: 0.7940157859120518
  saturation: 0.07042541797272861
  rhythmicContrast: 0.878632455598563
purpose: []
